# The finally Clause

The try...catch construct may have one more code clause : finally

If it exists it runs in all cause :

after try if there were no errors 
after catch if there were errors.

If there is a return in try, finally is executed just before the control returns to the outer code.

